version: 2

# Build using Read the Docs defaults, but you can also define Python dependencies here if needed
build:
  image: latest

# You aren't using Sphinx or MkDocs, so skip these
sphinx:
  builder: html

# Optionally skip installing MkDocs if you don't need it
python:
  install:
    - method: pip
      path: .

# Set the type of documentation you're serving, this can be custom static HTML files
formats:
  - htmlzip
  - PDF

# Include all files in the directory, unless specified otherwise
include:
  - docs/

# Specify the directory where your documentation lives, if it's not the root directory
docs_dir: docs

# Optionally define any environment variables if needed
